[env]
_.vfox-pulumi = { module_path = "." } # Sets GO_VERSION_MISE and PULUMI_VERSION_MISE

[tools]
node = "24.12.0"
"npm:yarn" = "1.22.22"
"github:pulumi/pulumictl" = '0.0.50'
# TODO: we may not need 'get_env' once https://github.com/jdx/mise/discussions/6339 is fixed
go = "{{ get_env(name='GO_VERSION_MISE', default='latest') }}"
pulumi = "3.213.0"
gotestsum = "latest"

[settings]
experimental = true # Required for Go binaries (e.g. pulumictl).
lockfile = false

[plugins]
vfox-pulumi = "https://github.com/pulumi/vfox-pulumi"
